### ISSUE TITLE
加载不出来

### ISSUE THREAD

**Issue by nidbCN** [JLChnToZ/nodebb-plugin-bilibili#11]
这是我服务器的锅还是插件的锅还是b站改接口了？
![default](https://user-images.githubusercontent.com/36162655/41678339-6661b8e6-74fd-11e8-94b0-2bd3399840bc.PNG)

**Comment by clearw5** [comment]
使用 https://github.com/hyb1996/nodebb-plugin-bilibili

**Comment by JLChnToZ** [comment]
Merged and published, plz open again if still not OK
